### ISSUE TITLE
Attempt to read property "volume" on null

### ISSUE THREAD

**Issue by tfk-kaare** [TromsFylkestrafikk/ragnarok-statens_vegvesen#6]
```
Attempt to read property "volume" on null
Occured in /var/www/ragnarok/vendor/ragnarok/svv/src/Services/SvvImporter.php(77)
- #0 /var/www/ragnarok/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
- #1 /var/www/ragnarok/vendor/ragnarok/svv/src/Services/SvvImporter.php(77): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
- #2 /var/www/ragnarok/vendor/ragnarok/svv/src/Sinks/SinkSvv.php(73): Ragnarok\Svv\Services\SvvImporter->import()
- #3 /var/www/ragnarok/app/Services/SinkHandler.php(174): Ragnarok\Svv\Sinks\SinkSvv->import()
- #4 /var/www/ragnarok/app/Services/SinkHandler.php(235): App\Services\SinkHandler->App\Services\{closure}()
- #5 /var/www/ragnarok/app/Services/SinkHandler.php(176): App\Services\SinkHandler->doRunOperation()
- #6 /var/www/ragnarok/app/Jobs/ImportChunk.php(41): App\Services\SinkHandler->importChunk() 
```

**Comment by tfk-kaare** [comment]
This first occurs on chunk 2024-03-11
